<x-auth-layout title="Set new password | TravelConnect">
    <main class="flex min-h-screen items-center justify-center px-6 py-12">
        <section class="w-full max-w-md">
            <div class="border-b border-[#dbe3e5] pb-7"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#e76f51]">Account recovery</p><h1 class="mt-3 font-serif text-4xl leading-tight tracking-tight">Create a new password</h1><p class="mt-4 text-sm leading-6 text-[#607985]">Your email has been verified. Choose a strong new password for your account.</p></div>
            @if ($errors->any())
                <div class="mt-5 flex items-center gap-3 rounded-xl border border-[#fda29b] bg-[#fef3f2] px-4 py-3 text-sm font-semibold text-[#b42318]" role="alert"><span class="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#f04438] text-xs text-white" aria-hidden="true">!</span><span>{{ $errors->first() }}</span></div>
            @endif
            <form action="{{ route('password.update') }}" method="POST" class="mt-8 grid gap-5">@csrf<label class="grid gap-2 text-sm font-semibold" for="password">New password<span class="relative"><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#e76f51]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="4" y="10" width="16" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><input id="password" type="password" name="password" autocomplete="new-password" required class="w-full rounded-xl border border-[#d7e0e1] bg-white py-3 pl-12 pr-4 font-normal outline-none focus:border-[#e76f51] focus:ring-2 focus:ring-[#e76f51]/15"></span></label><label class="grid gap-2 text-sm font-semibold" for="password_confirmation">Confirm password<span class="relative"><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#e76f51]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="4" y="10" width="16" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><input id="password_confirmation" type="password" name="password_confirmation" autocomplete="new-password" required class="w-full rounded-xl border border-[#d7e0e1] bg-white py-3 pl-12 pr-4 font-normal outline-none focus:border-[#e76f51] focus:ring-2 focus:ring-[#e76f51]/15"></span></label><button type="submit" data-loading-submit class="rounded-xl bg-[#e76f51] px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#d95f42]"><span data-submit-label>Save new password</span><span data-submit-spinner class="hidden"></span></button></form>
        </section>
    </main>
</x-auth-layout>
