<x-account-shell title="{{ __('messages.settings') }} | TravelConnect">
    <main data-account-settings class="min-h-screen bg-[#f7f8f6] px-5 py-8 text-[#173042] sm:px-8 lg:px-10 lg:py-10">
        <div class="mx-auto max-w-3xl">
            <div class="flex items-center justify-between border-b border-[#e4e9e7] pb-6">
                <div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#e76f51]">{{ __('messages.account') }}</p><h1 class="mt-2 font-serif text-4xl tracking-tight">{{ __('messages.settings') }}</h1><p class="mt-3 text-sm text-[#607985]">{{ __('messages.settings_intro') }}</p></div>
                <a href="{{ route('dashboard', ['lang' => app()->getLocale()]) }}" class="text-sm font-bold text-[#e76f51]">{{ __('messages.back_to_dashboard') }}</a>
            </div>
            <section class="mt-8 border border-[#e4e9e7] bg-white p-6 sm:p-8"><h2 class="text-lg font-bold">{{ __('messages.profile_information') }}</h2><form action="{{ route('settings.profile') }}" method="POST" class="mt-6 grid gap-5">@csrf @method('PUT')<label class="grid gap-2 text-sm font-semibold">{{ __('messages.full_name') }}<input type="text" name="name" value="{{ old('name', auth()->user()->name) }}" required class="rounded-xl border border-[#d7e0e1] px-4 py-3 font-normal outline-none focus:border-[#e76f51]"></label><label class="grid gap-2 text-sm font-semibold">{{ __('messages.email_address') }}<input type="email" name="email" value="{{ old('email', auth()->user()->email) }}" required class="rounded-xl border border-[#d7e0e1] px-4 py-3 font-normal outline-none focus:border-[#e76f51]"></label><label class="grid gap-2 text-sm font-semibold">{{ __('messages.phone') }}<input type="tel" name="phone" value="{{ old('phone', auth()->user()->phone) }}" class="rounded-xl border border-[#d7e0e1] px-4 py-3 font-normal outline-none focus:border-[#e76f51]"></label><button type="submit" class="w-fit rounded-xl bg-[#173042] px-5 py-3 text-sm font-bold text-white">{{ __('messages.save_changes') }}</button></form>@if ($errors->any())<p class="mt-3 text-sm font-semibold text-[#b42318]">{{ $errors->first() }}</p>@endif</section>
            <section class="mt-5 border border-[#e4e9e7] bg-white p-6 sm:p-8"><div class="flex items-center gap-4"><div class="flex h-16 w-16 items-center justify-center overflow-hidden rounded-full bg-[#173042] text-xl font-bold text-white">@if (auth()->user()->profile_photo_path)<img src="{{ asset('storage/'.auth()->user()->profile_photo_path) }}" alt="{{ auth()->user()->name }}" class="h-full w-full object-cover">@else{{ str(auth()->user()->name)->substr(0, 1)->upper() }}@endif</div><div><h2 class="text-lg font-bold">{{ __('messages.profile_photo') }}</h2><p class="mt-1 text-sm text-[#607985]">{{ __('messages.profile_photo_hint') }}</p></div></div><form action="{{ route('settings.profile-photo') }}" method="POST" enctype="multipart/form-data" class="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end">@csrf<label class="flex-1 text-sm font-semibold">{{ __('messages.choose_photo') }}<input type="file" name="profile_photo" accept="image/*" required class="mt-2 block w-full rounded-xl border border-[#d7e0e1] bg-white p-2 text-sm"></label><button type="submit" class="rounded-xl bg-[#e76f51] px-5 py-3 text-sm font-bold text-white">{{ __('messages.upload_photo') }}</button></form>@if (session('status'))<p class="mt-3 text-sm font-semibold text-[#2f9e7a]">{{ session('status') }}</p>@endif</section>
        </div>
    </main>
</x-account-shell>