@props(['overlay' => false])
<header class="sticky top-0 z-30 border-b border-[#dbe3e5] bg-white/95 text-[#173042] shadow-[0_2px_12px_rgba(23,48,66,.06)] backdrop-blur">
    <nav class="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-8" aria-label="Main navigation">
        <a href="{{ route('home') }}" class="flex items-center gap-3 text-lg font-semibold tracking-tight text-[#173042]">
            <span class="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-white shadow-sm"><img src="{{ asset('images/logo.png') }}" alt="TravelConnect logo" class="h-full w-full object-contain"></span>
            <span>Travel<span class="font-normal text-[#e76f51]">Connect</span></span>
        </a>
        <div class="hidden items-center gap-8 text-sm font-medium text-[#607985] md:flex">
            <a href="{{ route('home') }}" class="group relative py-2 transition hover:text-[#e76f51] {{ request()->routeIs('home') ? 'text-[#e76f51]' : '' }}">Home<span class="absolute inset-x-0 bottom-0 h-0.5 origin-left bg-[#e76f51] transition-transform {{ request()->routeIs('home') ? 'scale-x-100' : 'scale-x-0 group-hover:scale-x-100' }}"></span></a>
            <a href="{{ route('discover') }}" class="group relative py-2 transition hover:text-[#e76f51] {{ request()->routeIs('discover') || request()->routeIs('agency.show') ? 'text-[#e76f51]' : '' }}">Agencies<span class="absolute inset-x-0 bottom-0 h-0.5 origin-left bg-[#e76f51] transition-transform {{ request()->routeIs('discover') || request()->routeIs('agency.show') ? 'scale-x-100' : 'scale-x-0 group-hover:scale-x-100' }}"></span></a>
            <div class="group relative"><button type="button" class="flex items-center gap-1.5 py-2 transition hover:text-[#e76f51]">About <span class="text-[10px]" aria-hidden="true">▾</span></button><div class="invisible absolute left-1/2 top-full z-40 w-48 -translate-x-1/2 translate-y-2 border border-[#dbe3e5] bg-white p-2 opacity-0 shadow-[0_14px_30px_rgba(23,48,66,.12)] transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100"><a href="{{ route('how-it-works') }}" class="block px-3 py-2.5 text-sm text-[#607985] hover:bg-[#f1f6f4] hover:text-[#173042]">How it works</a><a href="{{ route('for-agencies') }}" class="block px-3 py-2.5 text-sm text-[#607985] hover:bg-[#f1f6f4] hover:text-[#173042]">For agencies</a></div></div>
            <div class="group relative"><button type="button" class="flex items-center gap-1.5 py-2 transition hover:text-[#e76f51]">Contact <span class="text-[10px]" aria-hidden="true">▾</span></button><div class="invisible absolute left-1/2 top-full z-40 w-48 -translate-x-1/2 translate-y-2 border border-[#dbe3e5] bg-white p-2 opacity-0 shadow-[0_14px_30px_rgba(23,48,66,.12)] transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100"><a href="mailto:hello@travelconnect.test" class="block px-3 py-2.5 text-sm text-[#607985] hover:bg-[#f1f6f4] hover:text-[#173042]">Email TravelConnect</a><a href="{{ route('for-agencies') }}#resources" class="block px-3 py-2.5 text-sm text-[#607985] hover:bg-[#f1f6f4] hover:text-[#173042]">Agency resources</a></div></div>
        </div>
        <div class="flex items-center gap-3 text-sm font-semibold">
            <div class="hidden items-center rounded-lg border border-[#dbe3e5] p-1 text-xs font-bold sm:flex" aria-label="Language selection"><a href="{{ request()->fullUrlWithQuery(['lang' => 'en']) }}" class="rounded-md px-2 py-1 {{ request('lang', 'en') === 'en' ? 'bg-[#173042] text-white' : 'text-[#607985] hover:text-[#173042]' }}">EN</a><a href="{{ request()->fullUrlWithQuery(['lang' => 'fr']) }}" class="rounded-md px-2 py-1 {{ request('lang') === 'fr' ? 'bg-[#173042] text-white' : 'text-[#607985] hover:text-[#173042]' }}">FR</a></div>
            <a href="{{ route('login') }}" data-loading-link class="hidden px-3 py-2 text-[#607985] transition hover:text-[#173042] sm:block">Log in</a>
            <a href="{{ route('register') }}" class="hidden rounded-full bg-[#173042] px-5 py-2.5 text-white shadow-sm transition hover:bg-[#26495d] sm:inline-flex">Create account</a>
            <button type="button" data-menu-toggle aria-expanded="false" aria-controls="mobile-menu" class="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg border border-[#dbe3e5] text-[#173042] md:hidden"><span class="sr-only">Open navigation</span><span class="text-xl leading-none" aria-hidden="true">&#9776;</span></button>
        </div>
    </nav>
    <div data-mobile-backdrop class="fixed inset-0 z-40 hidden bg-[#102936]/55 md:hidden"></div>
    <div id="mobile-menu" data-mobile-menu class="fixed bottom-0 right-0 top-0 z-50 hidden w-[min(88vw,360px)] border-l border-[#e7eceb] bg-white px-6 py-6 text-[#173042] shadow-2xl md:hidden">
        <div class="flex items-center justify-between border-b border-[#e7eceb] pb-5"><a href="{{ route('home') }}" class="flex items-center gap-3 text-lg font-semibold"><span class="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-[#fbfaf7]"><img src="{{ asset('images/logo.png') }}" alt="TravelConnect logo" class="h-full w-full object-contain"></span><span>Travel<span class="font-normal text-[#e76f51]">Connect</span></span></a><button type="button" data-menu-close aria-label="Close navigation" class="flex h-10 w-10 items-center justify-center rounded-lg border border-[#dbe3e5] text-xl">&times;</button></div>
        <div class="mt-8 grid gap-2 text-sm font-semibold">
            <a href="{{ route('home') }}" class="rounded-lg border-l-2 px-3 py-3 hover:bg-[#f1f6f4] {{ request()->routeIs('home') ? 'border-[#e76f51] bg-[#f1f6f4] text-[#e76f51]' : 'border-transparent' }}">Home</a>
            <a href="{{ route('login') }}" data-loading-link class="rounded-lg border-l-2 px-3 py-3 hover:bg-[#f1f6f4] {{ request()->routeIs('login') ? 'border-[#e76f51] bg-[#f1f6f4] text-[#e76f51]' : 'border-transparent' }}">Log in</a>
            <a href="{{ route('discover') }}" class="rounded-lg border-l-2 px-3 py-3 hover:bg-[#f1f6f4] {{ request()->routeIs('discover') || request()->routeIs('agency.show') ? 'border-[#e76f51] bg-[#f1f6f4] text-[#e76f51]' : 'border-transparent' }}">Agency directory</a>
            <details class="group rounded-lg border-l-2 border-transparent"><summary class="cursor-pointer list-none rounded-lg px-3 py-3 hover:bg-[#f1f6f4]">About <span class="float-right text-[#8a9ba0]" aria-hidden="true">▾</span></summary><div class="grid gap-1 pb-2 pl-3"><a href="{{ route('how-it-works') }}" class="rounded-lg px-3 py-2 text-sm text-[#607985] hover:bg-[#f1f6f4]">How it works</a><a href="{{ route('for-agencies') }}" class="rounded-lg px-3 py-2 text-sm text-[#607985] hover:bg-[#f1f6f4]">For agencies</a></div></details>
            <details class="group rounded-lg border-l-2 border-transparent"><summary class="cursor-pointer list-none rounded-lg px-3 py-3 hover:bg-[#f1f6f4]">Contact <span class="float-right text-[#8a9ba0]" aria-hidden="true">▾</span></summary><div class="grid gap-1 pb-2 pl-3"><a href="mailto:hello@travelconnect.test" class="rounded-lg px-3 py-2 text-sm text-[#607985] hover:bg-[#f1f6f4]">Email TravelConnect</a><a href="{{ route('for-agencies') }}#resources" class="rounded-lg px-3 py-2 text-sm text-[#607985] hover:bg-[#f1f6f4]">Agency resources</a></div></details>
        </div>
        <div class="mt-8 border-t border-[#e7eceb] pt-6"><p class="text-xs font-bold uppercase tracking-[.16em] text-[#8a9ba0]">Language</p><div class="mt-3 flex gap-2"><a href="{{ request()->fullUrlWithQuery(['lang' => 'en']) }}" class="flex-1 rounded-lg border px-3 py-2.5 text-center text-sm font-bold {{ request('lang', 'en') === 'en' ? 'border-[#173042] bg-[#173042] text-white' : 'border-[#dbe3e5] text-[#607985]' }}">English</a><a href="{{ request()->fullUrlWithQuery(['lang' => 'fr']) }}" class="flex-1 rounded-lg border px-3 py-2.5 text-center text-sm font-bold {{ request('lang') === 'fr' ? 'border-[#173042] bg-[#173042] text-white' : 'border-[#dbe3e5] text-[#607985]' }}">Français</a></div></div>
        <a href="{{ route('register') }}" class="mt-8 block rounded-xl bg-[#e76f51] px-4 py-3 text-center text-sm font-bold text-white transition hover:bg-[#d95f42]">Register your agency <span class="ml-2" aria-hidden="true">&rarr;</span></a>
    </div>
</header>
