<footer class="bg-[#102936] text-white">
    <div class="mx-auto max-w-7xl px-6 py-16 lg:px-8">
        <div class="grid gap-12 border-b border-white/15 pb-14 lg:grid-cols-[1.4fr_1fr_1fr_1.2fr]">
            <div class="max-w-sm">
                <a href="{{ route('home') }}" class="flex items-center gap-3 text-lg font-semibold tracking-tight"><span class="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-white"><img src="{{ asset('images/logo.png') }}" alt="TravelConnect logo" class="h-full w-full object-contain"></span><span>Travel<span class="font-normal text-[#f6c9bb]">Connect</span></span></a>
                <p class="mt-4 max-w-xs text-xl font-serif leading-8 text-white">{{ __('messages.travelconnect') }}</p>
                <p class="mt-3 max-w-sm text-sm leading-6 text-white/55">{{ __('messages.travelers_and_agencies_description') }}</p>
                <div class="mt-5 flex gap-3"><a href="#" aria-label="Instagram" class="flex h-9 w-9 items-center justify-center rounded-full border border-white/20 text-xs hover:border-[#e76f51]">IG</a><a href="#" aria-label="Facebook" class="flex h-9 w-9 items-center justify-center rounded-full border border-white/20 text-xs hover:border-[#e76f51]">FB</a><a href="#" aria-label="LinkedIn" class="flex h-9 w-9 items-center justify-center rounded-full border border-white/20 text-xs hover:border-[#e76f51]">IN</a></div>
            </div>
            <div><h2 class="text-xs font-bold uppercase tracking-[.18em] text-[#f6c9bb]">{{ __('messages.explore') }}</h2><div class="mt-6 grid gap-4 text-sm text-white/65"><a href="{{ route('home') }}" class="hover:text-white">{{ __('messages.home') }}</a><a href="{{ route('discover') }}" class="hover:text-white">{{ __('messages.find_an_agency') }}</a><a href="{{ route('how-it-works') }}" class="hover:text-white">{{ __('messages.how_it_works') }}</a><a href="{{ route('home') }}#featured-agencies" class="hover:text-white">{{ __('messages.featured_agencies') }}</a></div></div>
            <div><h2 class="text-xs font-bold uppercase tracking-[.18em] text-[#f6c9bb]">{{ __('messages.for_agencies') }}</h2><div class="mt-6 grid gap-4 text-sm text-white/65"><a href="{{ route('for-agencies') }}" class="hover:text-white">{{ __('messages.join_travelconnect') }}</a><a href="{{ route('for-agencies') }}#verification" class="hover:text-white">{{ __('messages.verify') }}</a><a href="{{ route('for-agencies') }}#resources" class="hover:text-white">{{ __('messages.agency_resources') }}</a></div><div class="mt-8 text-sm leading-6 text-white/55"><p class="font-semibold text-white">{{ __('messages.have_a_question') }}</p><a href="mailto:hello@travelconnect.test" class="hover:text-[#f6c9bb]">hello@travelconnect.test</a></div></div>
            <div><h2 class="text-xs font-bold uppercase tracking-[.18em] text-[#f6c9bb]">{{ __('messages.stay_inspired') }}</h2><p class="mt-6 text-sm leading-6 text-white/60">{{ __('messages.monthly_note') }}</p><form action="#" class="mt-5 grid gap-3"><label class="sr-only" for="footer-email">{{ __('messages.email_address') }}</label><input id="footer-email" type="email" placeholder="{{ __('messages.your_email_address') }}" class="w-full rounded-lg border border-white/15 bg-white/10 px-4 py-3 text-sm text-white outline-none placeholder:text-white/40 focus:border-[#e76f51]"><button type="submit" class="rounded-lg bg-[#e76f51] px-4 py-3 text-sm font-bold text-white hover:bg-[#d95f42]">{{ __('messages.subscribe_to_journal') }} <span class="ml-2">&rarr;</span></button></form></div>
        </div>
        <div class="flex flex-col gap-3 pt-5 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><p>&copy; {{ date('Y') }} {{ __('messages.travelconnect') }}. {{ __('messages.all_rights_reserved') }}</p><div class="flex flex-wrap gap-5"><a href="{{ route('privacy') }}" class="hover:text-white">{{ __('messages.privacy_policy') }}</a><a href="{{ route('terms') }}" class="hover:text-white">{{ __('messages.terms_of_use') }}</a><a href="{{ route('accessibility') }}" class="hover:text-white">{{ __('messages.accessibility') }}</a></div><p>{{ __('messages.made_for_meaningful_journeys') }}</p></div>
    </div>
</footer>
