<x-public-layout :title="$agency['name'].' | TravelConnect'" description="Explore this verified travel agency, compare trust signals, and connect on TravelConnect.">
    <x-site-header />
    <main>
        <div class="mx-auto max-w-7xl px-6 pt-8 text-sm text-[#607985] lg:px-8"><a href="{{ route('discover') }}" class="font-semibold hover:text-[#e76f51]">Agency directory</a><span class="mx-2">/</span><span>{{ $agency['name'] }}</span></div>
        <section class="relative mt-6 h-[360px] overflow-hidden bg-[#173042] sm:h-[440px]"><img src="{{ $agency['cover'] }}" alt="{{ $agency['name'] }} destination" class="absolute inset-0 h-full w-full object-cover opacity-75"><div class="absolute inset-0 bg-[linear-gradient(90deg,rgba(16,39,54,.92),rgba(23,48,66,.18))]"></div><div class="relative mx-auto flex h-full max-w-7xl items-end px-6 pb-10 lg:px-8"><div class="max-w-3xl text-white"><span class="inline-flex rounded-full bg-white px-3 py-1.5 text-xs font-bold text-[#173042]">Verified agency</span><h1 class="mt-5 font-serif text-4xl leading-tight sm:text-6xl">{{ $agency['name'] }}</h1><p class="mt-4 text-base text-white/80">{{ $agency['country'] }} <span class="mx-2 text-white/50">|</span> {{ $agency['service'] }}</p></div></div></section>
        <section class="mx-auto grid max-w-7xl gap-12 px-6 py-12 lg:grid-cols-[1.25fr_.75fr] lg:px-8 lg:py-16">
            <div>
                <div class="grid grid-cols-2 gap-4 border-b border-[#e7eceb] pb-8 sm:grid-cols-4"><div><p class="text-2xl font-bold text-[#173042]">{{ $agency['rating'] }} <span class="text-[#e76f51]">★</span></p><p class="mt-1 text-xs text-[#607985]">Overall rating</p></div><div><p class="text-2xl font-bold text-[#173042]">{{ $agency['reviews'] }}</p><p class="mt-1 text-xs text-[#607985]">Published reviews</p></div><div><p class="text-2xl font-bold text-[#173042]">4 hrs</p><p class="mt-1 text-xs text-[#607985]">Response time</p></div><div><p class="text-2xl font-bold text-[#173042]">100%</p><p class="mt-1 text-xs text-[#607985]">Verified details</p></div></div>
                <h2 class="mt-10 font-serif text-3xl tracking-tight sm:text-4xl">About this agency</h2><p class="mt-5 max-w-2xl text-base leading-8 text-[#607985]">{{ $agency['description'] }}</p>
                <div class="mt-10 grid gap-4 border-y border-[#e7eceb] py-6 sm:grid-cols-2"><div><p class="text-xs font-bold uppercase tracking-[.15em] text-[#607985]">Specialty</p><p class="mt-2 font-semibold text-[#173042]">{{ $agency['service'] }}</p></div><div><p class="text-xs font-bold uppercase tracking-[.15em] text-[#607985]">Based in</p><p class="mt-2 font-semibold text-[#173042]">{{ $agency['country'] }}</p></div></div>
                <h2 class="mt-14 font-serif text-3xl tracking-tight sm:text-4xl">Travel experiences</h2><div class="mt-6 grid gap-4 sm:grid-cols-2"><img src="{{ $gallery[0]['image'] }}" alt="{{ $gallery[0]['alt'] }}" class="h-64 w-full rounded-xl object-cover"><img src="{{ $gallery[1]['image'] }}" alt="{{ $gallery[1]['alt'] }}" class="h-64 w-full rounded-xl object-cover"></div><img src="{{ $gallery[2]['image'] }}" alt="{{ $gallery[2]['alt'] }}" class="mt-4 h-72 w-full rounded-xl object-cover">
                <section id="reviews" class="mt-14 border-t border-[#e7eceb] pt-12"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-[#e76f51]">Verified feedback</p><h2 class="mt-3 font-serif text-3xl tracking-tight sm:text-4xl">Reviews from travelers</h2></div><a href="{{ route('login') }}" class="text-sm font-bold text-[#e76f51] hover:text-[#b94d35]">Sign in to write a review</a></div><div class="mt-8 grid gap-3 sm:grid-cols-[.8fr_1.2fr]"><div class="rounded-xl bg-[#f1f6f4] p-5"><p class="text-4xl font-bold text-[#173042]">{{ $agency['rating'] }} <span class="text-[#e76f51]">★</span></p><p class="mt-2 text-sm text-[#607985]">Based on {{ $agency['reviews'] }} reviews</p><div class="mt-5 grid gap-2 text-xs text-[#607985]"><p>5 stars <span class="ml-2 inline-block h-2 w-32 rounded-full bg-[#e76f51]"></span></p><p>4 stars <span class="ml-2 inline-block h-2 w-20 rounded-full bg-[#f3b2a1]"></span></p><p>3 stars <span class="ml-2 inline-block h-2 w-8 rounded-full bg-[#dbe3e5]"></span></p></div></div><div class="grid gap-5"><article class="border-b border-[#e7eceb] pb-5"><div class="flex items-center justify-between"><p class="font-bold text-[#173042]">Excellent local knowledge</p><span class="text-sm font-bold text-[#e76f51]">5.0 ★</span></div><p class="mt-2 text-sm leading-6 text-[#607985]">“Thoughtful from the first conversation. The local knowledge made every part of the trip feel easy.”</p><p class="mt-2 text-xs text-[#607985]">Verified traveler · 2 weeks ago</p></article><article><div class="flex items-center justify-between"><p class="font-bold text-[#173042]">Clear and reliable planning</p><span class="text-sm font-bold text-[#e76f51]">5.0 ★</span></div><p class="mt-2 text-sm leading-6 text-[#607985]">“Everything was well organized, and the team responded quickly whenever we had a question.”</p><p class="mt-2 text-xs text-[#607985]">Verified traveler · 1 month ago</p></article></div></div></section>
            </div>
            <aside><div class="sticky top-8 rounded-xl border border-[#e7eceb] bg-white p-6 shadow-[0_12px_30px_rgba(23,48,66,.06)]"><h2 class="text-lg font-bold text-[#173042]">Connect with this agency</h2><p class="mt-3 text-sm leading-6 text-[#607985]">Tell the agency what you are looking for and start a conversation.</p><button type="button" class="mt-6 w-full rounded-xl bg-[#e76f51] px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#d95f42]">Send an inquiry <span class="ml-2" aria-hidden="true">&rarr;</span></button><button type="button" data-favorite-toggle aria-pressed="false" class="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#d7e0e1] px-5 py-3.5 text-sm font-bold text-[#173042] transition hover:border-[#e76f51] hover:text-[#e76f51]"><span data-favorite-icon aria-hidden="true">&#9825;</span><span data-favorite-label>Save agency</span></button><div class="mt-6 border-t border-[#e7eceb] pt-5 text-sm text-[#607985]"><p class="font-semibold text-[#173042]">Trust signals</p><p class="mt-2">Business identity reviewed</p><p class="mt-1">Verified agency information</p><p class="mt-1">Traveler reviews published</p></div></div></aside>
        </section>
        <section class="mx-auto max-w-7xl border-t border-[#e7eceb] px-6 py-12 lg:px-8"><div class="max-w-2xl"><p class="text-xs font-bold uppercase tracking-[.18em] text-[#e76f51]">Share your experience</p><h2 class="mt-3 font-serif text-3xl tracking-tight">Rate this agency</h2><p class="mt-3 text-sm leading-6 text-[#607985]">Choose a rating. Sign in to publish your rating and comment.</p><div class="mt-4 flex gap-1" role="group" aria-label="Choose a rating"><button type="button" data-rating="1" aria-label="1 star" class="text-3xl text-[#d7e0e1] transition hover:text-[#e76f51]">★</button><button type="button" data-rating="2" aria-label="2 stars" class="text-3xl text-[#d7e0e1] transition hover:text-[#e76f51]">★</button><button type="button" data-rating="3" aria-label="3 stars" class="text-3xl text-[#d7e0e1] transition hover:text-[#e76f51]">★</button><button type="button" data-rating="4" aria-label="4 stars" class="text-3xl text-[#d7e0e1] transition hover:text-[#e76f51]">★</button><button type="button" data-rating="5" aria-label="5 stars" class="text-3xl text-[#d7e0e1] transition hover:text-[#e76f51]">★</button></div><p data-rating-message class="mt-2 text-xs text-[#607985]">No rating selected.</p><a href="{{ route('login') }}" class="mt-5 inline-flex rounded-xl bg-[#173042] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#26495d]">Sign in to publish review</a></div></section>
    </main>
    <x-site-footer />
</x-public-layout>
