<x-public-layout title="Explore agencies | TravelConnect" description="Discover trusted travel agencies and connect with the right expert for your journey.">
    <x-site-header />
    <main class="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-24">
        <p class="text-xs font-bold uppercase tracking-[.2em] text-[#e76f51]">The TravelConnect directory</p>
        <h1 class="mt-4 max-w-2xl font-serif text-5xl tracking-tight sm:text-6xl">Find the right agency for your journey.</h1>
        <p class="mt-6 max-w-xl text-lg leading-8 text-[#607985]">Compare trusted agencies by destination, travel style, and the expertise they bring to every detail.</p>
        <div class="mt-12 flex flex-col gap-3 rounded-2xl bg-white p-3 shadow-[0_12px_40px_rgba(23,48,66,.08)] sm:flex-row"><input type="search" placeholder="Search a destination or agency" class="flex-1 rounded-xl bg-[#f1f6f4] px-5 py-3 text-sm outline-none focus:ring-2 focus:ring-[#e76f51]"><select class="rounded-xl bg-[#f1f6f4] px-5 py-3 text-sm outline-none"><option>All travel styles</option><option>Adventure travel</option><option>Luxury escapes</option><option>Family holidays</option></select><button class="rounded-xl bg-[#e76f51] px-7 py-3 text-sm font-bold text-white">Search agencies</button></div>
        <div class="mt-16 grid gap-6 md:grid-cols-3"><x-agency-card name="Atlas Horizon Voyages" image="https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=85" alt="Mountain lake destination" description="Tailor-made adventures across Europe and beyond." country="France" service="Adventure travel" /><x-agency-card name="Lumiere Routes" image="https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=900&q=85" alt="Tropical island coastline" description="Slow travel and beautiful escapes, thoughtfully planned." country="Portugal" service="Luxury escapes" rating="4.8" /><x-agency-card name="Northstar Escapes" image="https://images.unsplash.com/photo-1522083165195-3424ed129620?auto=format&fit=crop&w=900&q=85" alt="Traveler looking over a scenic valley" description="Family journeys built around the moments that matter." country="Canada" service="Family holidays" /></div>
    <section class="mt-20 border-t border-[#e7eceb] pt-14 text-center"><p class="text-sm text-[#607985]">Are you a travel professional?</p><a href="{{ route('register.agency') }}" class="mt-4 inline-flex rounded-xl bg-[#173042] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#26495d]">Register your agency <span class="ml-3" aria-hidden="true">&rarr;</span></a></section>
    </main>
    <x-site-footer />
</x-public-layout>
