<x-public-layout title="TravelConnect | The agency platform for better journeys" description="Build a trusted travel agency presence, manage inquiries, and grow with TravelConnect.">
    <x-site-header overlay />
    <main id="top">
        <section class="relative isolate min-h-[720px] overflow-hidden bg-[#173042]">
            <img src="{{ asset('images/destinations/new-york.jpg') }}" alt="New York City skyline with the Empire State Building" class="absolute inset-0 -z-20 h-full w-full object-cover object-center opacity-70">
            <div class="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(16,39,54,.9)_0%,rgba(23,48,66,.62)_48%,rgba(23,48,66,.18)_100%)]"></div>
            <div class="mx-auto flex max-w-7xl flex-col justify-center px-6 pb-32 pt-44 lg:px-8">
                <div class="max-w-2xl"><p class="mb-6 text-xs font-bold uppercase tracking-[.25em] text-[#f6c9bb]">Trusted travel connections</p><h1 class="max-w-xl font-serif text-5xl leading-[1.04] tracking-tight text-white sm:text-6xl lg:text-7xl">Find the right agency. Grow your travel business.</h1><p class="mt-7 max-w-lg text-lg leading-8 text-white/80">Travelers discover trusted experts, while agencies build their profile, earn confidence, and manage new inquiries in one place.</p></div>
                <form action="{{ route('discover') }}" method="GET" class="mt-10 max-w-3xl bg-white p-2 shadow-[0_16px_40px_rgba(0,0,0,.18)]"><div class="flex flex-col gap-2 sm:flex-row"><label class="relative flex-1"><span class="sr-only">Search destination or agency</span><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#e76f51]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/></svg><input type="search" name="search" placeholder="Where do you want to travel?" class="w-full border border-[#173042] bg-white py-3.5 pl-12 pr-4 text-sm text-[#173042] outline-none placeholder:text-[#8a9ba0] focus:border-[#e76f51] focus:ring-2 focus:ring-[#e76f51]/15"></label><button type="submit" class="inline-flex items-center justify-center gap-2 bg-[#e76f51] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#d95f42]"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/></svg>Find an agency</button></div></form><div class="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-white/70"><span>Popular:</span><a href="{{ route('discover', ['destination' => 'France']) }}" class="font-semibold text-white underline decoration-white/30 underline-offset-4 hover:text-[#f6c9bb]">France</a><a href="{{ route('discover', ['service' => 'Adventure travel']) }}" class="font-semibold text-white underline decoration-white/30 underline-offset-4 hover:text-[#f6c9bb]">Adventure travel</a><a href="{{ route('discover', ['service' => 'Luxury escapes']) }}" class="font-semibold text-white underline decoration-white/30 underline-offset-4 hover:text-[#f6c9bb]">Luxury escapes</a></div>
            </div>
        </section>
        <section class="border-b border-[#e7eceb] bg-white" data-destination-carousel>
            <div class="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-20">
                <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
                    <div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#e76f51]">Popular destinations</p><h2 class="mt-3 font-serif text-4xl tracking-tight text-[#173042] sm:text-5xl">Where travelers are going next.</h2><p class="mt-4 max-w-xl text-base leading-7 text-[#607985]">Browse places people are exploring and find a trusted specialist for the journey.</p></div>
                    <div class="flex gap-2"><button type="button" data-destination-prev aria-label="Previous destinations" class="flex h-10 w-10 items-center justify-center rounded-full border border-[#173042] text-lg text-[#173042] transition hover:border-[#e76f51] hover:text-[#e76f51]">&larr;</button><button type="button" data-destination-next aria-label="Next destinations" class="flex h-10 w-10 items-center justify-center rounded-full border border-[#173042] text-lg text-[#173042] transition hover:border-[#e76f51] hover:text-[#e76f51]">&rarr;</button></div>
                </div>
                <div class="mt-10 overflow-hidden"><div data-destination-track class="flex transition-transform duration-500 ease-out">
                    @foreach ([['name' => 'Paris', 'country' => 'France', 'image' => 'paris.jpg', 'description' => 'Art, food, and timeless city escapes.'], ['name' => 'Santorini', 'country' => 'Greece', 'image' => 'santorini.jpg', 'description' => 'Island light, quiet villages, and sea views.'], ['name' => 'Marrakesh', 'country' => 'Morocco', 'image' => 'marrakesh.jpg', 'description' => 'Markets, riads, and journeys shaped by culture.'], ['name' => 'Bali', 'country' => 'Indonesia', 'image' => 'bali.jpg', 'description' => 'Wellness, coastline, and island discovery.'], ['name' => 'Kyoto', 'country' => 'Japan', 'image' => 'kyoto.jpg', 'description' => 'Temple paths, gardens, and considered travel.'], ['name' => 'New York', 'country' => 'United States', 'image' => 'new-york.jpg', 'description' => 'An energetic city break with endless character.']] as $destination)
                        <a href="{{ route('discover', ['search' => $destination['name']]) }}" class="group w-full shrink-0 pr-4 sm:w-1/2 lg:w-1/3"><div class="relative h-64 overflow-hidden"><img src="{{ asset('images/destinations/'.$destination['image']) }}" alt="{{ $destination['name'] }}, {{ $destination['country'] }}" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><span class="absolute bottom-4 left-4 bg-white px-3 py-1.5 text-xs font-bold text-[#173042]">{{ $destination['country'] }}</span></div><h3 class="mt-4 text-xl font-bold text-[#173042]">{{ $destination['name'] }}</h3><p class="mt-2 text-sm leading-6 text-[#607985]">{{ $destination['description'] }}</p></a>
                    @endforeach
                </div></div>
            </div>
        </section>
        <section id="featured-agencies" class="bg-[#f1f6f4]" data-carousel><div class="mx-auto max-w-7xl px-6 py-20 lg:px-8 lg:py-28"><div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#e76f51]">Built on trust</p><h2 class="mt-3 font-serif text-4xl tracking-tight text-[#173042] sm:text-5xl">A better standard for agencies.</h2></div><div class="flex items-center gap-3"><a href="{{ route('discover') }}" class="mr-3 text-sm font-bold text-[#e76f51]">View the agency directory <span aria-hidden="true">&rarr;</span></a><button type="button" data-carousel-prev aria-label="Previous agencies" class="flex h-10 w-10 items-center justify-center rounded-full border border-[#cbd9d8] text-lg hover:border-[#e76f51] hover:text-[#e76f51]">&larr;</button><button type="button" data-carousel-next aria-label="Next agencies" class="flex h-10 w-10 items-center justify-center rounded-full border border-[#cbd9d8] text-lg hover:border-[#e76f51] hover:text-[#e76f51]">&rarr;</button></div></div><div class="mt-12 overflow-hidden"><div data-carousel-track class="-mx-2 flex transition-transform duration-500 ease-out"><div class="w-full shrink-0 px-2 md:w-1/2 lg:w-1/3"><x-agency-card name="Atlas Horizon Voyages" image="https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=85" alt="Mountain lake destination" description="Tailor-made adventures across Europe and beyond." country="France" service="Adventure travel" /></div><div class="w-full shrink-0 px-2 md:w-1/2 lg:w-1/3"><x-agency-card name="Lumiere Routes" image="https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=900&q=85" alt="Tropical island coastline" description="Slow travel and beautiful escapes, thoughtfully planned." country="Portugal" service="Luxury escapes" rating="4.8" /></div><div class="w-full shrink-0 px-2 md:w-1/2 lg:w-1/3"><x-agency-card name="Northstar Escapes" image="https://images.unsplash.com/photo-1522083165195-3424ed129620?auto=format&fit=crop&w=900&q=85" alt="Traveler looking over a scenic valley" description="Family journeys built around the moments that matter." country="Canada" service="Family holidays" /></div><div class="w-full shrink-0 px-2 md:w-1/2 lg:w-1/3"><x-agency-card name="Sirocco Travel House" image="https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=85" alt="Desert dunes at sunset" description="Cultural journeys shaped by local knowledge." country="Morocco" service="Cultural tours" rating="4.7" /></div></div></div><div class="mt-6 flex justify-center gap-2" data-carousel-dots></div></div></section>
        <section id="how-it-works" class="border-y border-[#e7eceb] bg-white"><div class="mx-auto grid max-w-7xl gap-14 px-6 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#e76f51]">A better way to grow</p><h2 class="mt-3 max-w-md font-serif text-4xl tracking-tight sm:text-5xl">A stronger agency at every step.</h2><p class="mt-6 max-w-md leading-7 text-[#607985]">TravelConnect gives your business the tools to present its expertise, earn trust, and manage new opportunities.</p></div><div class="grid gap-10 sm:grid-cols-3"><div><span class="text-3xl font-serif text-[#e76f51]">01</span><h3 class="mt-5 text-lg font-semibold">Create</h3><p class="mt-3 text-sm leading-6 text-[#607985]">Build a complete profile for your agency.</p></div><div><span class="text-3xl font-serif text-[#e76f51]">02</span><h3 class="mt-5 text-lg font-semibold">Verify</h3><p class="mt-3 text-sm leading-6 text-[#607985]">Add trust with business verification.</p></div><div><span class="text-3xl font-serif text-[#e76f51]">03</span><h3 class="mt-5 text-lg font-semibold">Grow</h3><p class="mt-3 text-sm leading-6 text-[#607985]">Manage inquiries and win more business.</p></div></div></div></section>
        <section id="for-agencies" class="mx-auto max-w-7xl px-6 py-20 lg:px-8 lg:py-28"><div class="relative overflow-hidden rounded-3xl bg-[#173042] px-8 py-14 sm:px-14 lg:flex lg:items-center lg:justify-between lg:py-16"><div class="relative max-w-xl"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#f6c9bb]">For travel professionals</p><h2 class="mt-4 font-serif text-4xl tracking-tight text-white sm:text-5xl">Turn your expertise into someone’s best trip.</h2><p class="mt-5 leading-7 text-white/70">Build a profile, share your specialties, and connect with travelers who are ready to go.</p></div><a href="{{ route('for-agencies') }}" class="relative mt-8 inline-flex shrink-0 rounded-full bg-[#e76f51] px-6 py-3.5 text-sm font-bold text-white lg:mt-0">Join as an agency <span class="ml-3" aria-hidden="true">&rarr;</span></a></div></section>
    </main>
    <x-site-footer />
</x-public-layout>
